## Introduction to Tensors

In [26]:
#HI
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.9.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [27]:
# create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [28]:
# check the number of dimensions(use ndim for number of divisions)
scalar.ndim

0

In [29]:
#create a vector
vector = tf.constant([10,10])
vector.ndim,vector

(1, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [30]:
# create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix,matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 2)

In [31]:
#another matrix
another_matrix=tf.constant([[10.,7.],[3.,4.],[6.,9.]],dtype=tf.float16)
another_matrix,another_matrix.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[10.,  7.],
        [ 3.,  4.],
        [ 6.,  9.]], dtype=float16)>,
 2)

In [32]:
#increasing the number of dimensions
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[13,14,15],[16,17,18]]],dtype=tf.int32)
tensor,tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>,
 3)

1. Scalar is single number
2. Vector is a number with direction
3. Matrix is 2-d array of numbers
4. Tensor is an n-D array of numbers(where n can be a 0D[scalar] or 1D[Vector])

## Creating tensor with tf.Variable

In [33]:
# variable
changeable_tensor=tf.Variable([10,7],dtype=tf.float32)
unchangeable_tensor=tf.constant([10,7],dtype=tf.float32)
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>)

In [34]:
# changeable_tensor[0] = 12
# changeable_tensor


# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[85], line 1
# ----> 1 changeable_tensor[0] = 12
#       2 changeable_tensor

# TypeError: 'ResourceVariable' object does not support item assignment

In [35]:
#changing one of the elements in our changeable_tensor
changeable_tensor.assign([10,9])
#unchangeable_tensor[0].assign([10])
#print(unchangeable_tensor)
#therefore cannot change a constant tensor because it is constant


#AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([10.,  9.], dtype=float32)>

# Random tensors
tesnors with random size and random numbers

In [36]:
# create two random(but equal) tensors
random_1=tf.random.Generator.from_seed(7) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))

random_1,random_2

#are those two equal?
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in the tensor

In [37]:
# shuffle a tensor(useful when we need to shuffle our data so that the original order doesnt affect the learning)
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [6,9]],dtype=tf.float32)
# shuffling now
tf.random.set_seed(4)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 6.,  9.],
       [ 3.,  4.]], dtype=float32)>

### Other ways to make tensors

In [38]:
# Create a tensor of all ones and zeroes
tf.ones([10,7]),tf.zeros([10,7])

(<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
 array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(10, 7), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>)

## You can also turn numpy arrays into tensorflow tensors

In [39]:
#You can also turn numpy arrays into tensorflow tensors
import numpy as np
np_A=np.arange(1,25,dtype=np.int32)
print(np_A)
A=tf.constant(np_A,shape=(2,3,4))
A

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting informaation from tensors
1. Shape
2. Rank
3. Axis/dimension
4. Size

In [40]:
#Create a rank 4 tensor
rank_4_tensor=tf.zeros([2,3,4,5],dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [41]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [42]:
rank_4_tensor[0],rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
 array([[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],
 
        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]], dtype=int32)>,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [43]:
#Get various attributes of tensors
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions(rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in tensor: ",tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'int32'>
Number of dimensions(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in tensor:  120


### Indexing tensors

In [44]:
# Get the first two elements of each dimesnions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [45]:
#Get the first element from each dimension from each index except from the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [46]:
# Create a rank 2 dimensions
rank_2_tensor=tf.constant([[10,7],[6,9]],dtype=tf.int32)
rank_2_tensor,rank_2_tensor.ndim,rank_2_tensor.shape,tf.size(rank_2_tensor).numpy()

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 6,  9]], dtype=int32)>,
 2,
 TensorShape([2, 2]),
 4)

In [47]:
#Get last element of each row
rank_2_tensor[:,-1].numpy()

array([7, 9], dtype=int32)

In [48]:
# Adding extra dimesnion
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 6],
        [ 9]]], dtype=int32)>

In [49]:
example_understand=tf.constant([[10,7],[6,9]],dtype=tf.int32)
change_example=example_understand[:,:,tf.newaxis]
change_example

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 6],
        [ 9]]], dtype=int32)>

In [51]:
# Alternative to tf.new axis
tf.expand_dims(rank_2_tensor,axis=-1)   #axis->give the index where to expands

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 6],
        [ 9]]], dtype=int32)>

In [52]:
# Expand the 0 axis:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 6,  9]]], dtype=int32)>

### Manipulating tensors (tensor operations)

In [53]:
# Basic operations
tensor = tf.constant([[10,7],[3,4]])
tensor+10,tensor-10,tensor*10,tensor/10

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

In [54]:
# using tensorflow built-in functions too
# Faster execution when functions are used
tf.add(tensor,10),tf.subtract(tensor,10),tf.multiply(tensor,10),tf.divide(tensor,10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1. , 0.7],
        [0.3, 0.4]])>)

## Matrix Multiplication
In ml, matrix multiplication is one of the basic tesnor operations

In [55]:
print(tensor)
tensor2=tf.reshape(tensor,shape=(4,1))
tensor=tf.cast(tensor,dtype=tf.float32)
tensor.dtype

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


tf.float32

In [56]:
tf.matmul(tensor,tf.cast(tf.reshape(tensor2,shape=(2,2)),dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [57]:
tensor.shape

TensorShape([2, 2])

In [58]:
#matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [59]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [60]:
test1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
test2=tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(test1,test2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [61]:
# Matrix multiplication with python operator
test1 @ test2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [62]:
#matrix of same ndim cant be multiplied, so need to be reshaped
test2_copy=tf.reshape(test2,shape=(2,3))
tf.matmul(test2,test2_copy)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [63]:
# Tranpose
tf.transpose(test2).shape,test2.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

##### multiplying with tranpose is not same as multiplying by reshaping, they give different results because in tranpose, axes are changed, but in reshape only re-shuffling

In [65]:
tf.matmul(test2,tf.transpose(test2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

### The dot porduct
Matrix multiplication is also called as dot product
1. tf.matmul()
2. tf.tensordot()
3. @

In [66]:
# perform dot product on X and Y, this X or Y to be transposed
X=tf.constant([[1,2],[3,4],[5,6]])
Y=tf.constant([[7,8],[9,10],[11,12]])
print(X,Y)
tf.tensordot(tf.transpose(X),Y,axes=1)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [67]:
# Perform matrix multiplication X and Y(transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [68]:
# Perform matrix multiplication X and Y(reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# Check values of Y and transposed Y
print("Normal Y: \n",Y)
print("\nY reshaped: \n",tf.reshape(Y,shape=(2,3)))
print("\nY Transposed: \n",tf.transpose(Y))

Normal Y: 
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

Y reshaped: 
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Y Transposed: 
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing the datatype of the tensor

In [70]:
# Create a new tensore with default datatype
B = tf.constant([1.7,7.4])
print(B,B.dtype)

B = tf.cast(B,dtype=tf.float16)
print(B,B.dtype)

tf.Tensor([1.7 7.4], shape=(2,), dtype=float32) <dtype: 'float32'>
tf.Tensor([1.7 7.4], shape=(2,), dtype=float16) <dtype: 'float16'>


In [71]:
C=tf.constant([10,7])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [72]:
# change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 tf.float32)

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a small amount of values

In [73]:
# Getting the absolute values
D = tf.constant([-7,-10])
print(D)
tf.abs(D)

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#### forms of aggregation:
1. Get the minimum of tensor
2. Get the maximum of tensor
3. Get the mean of the tensor
4. Get the sum of the tensor

In [74]:
test = tf.constant(np.random.randint(0,100,size=50))
print(test)
print("Minimum: ",tf.reduce_min(test).numpy())
print("Maximum: ",tf.reduce_max(test).numpy())
print("mean: ",tf.reduce_mean(test).numpy())
print("Sum of all elements: ",tf.reduce_sum(test).numpy())
print("Varience: ",tf.math.reduce_variance(tf.cast(test,dtype=tf.float32)).numpy())
print("Standard deviation: ",tf.math.reduce_std(tf.cast(test,dtype=tf.float32)).numpy())

tf.Tensor(
[51 26 94  9 53 36 19 14 58 47 79 42 65 19 98 96 73 29 59 45  6 29 70 77
 86 74 19  1 99 14 34 70 12 51 75 94 61 88 84 22 53 21  8 74 21 33 75 87
  7 25], shape=(50,), dtype=int64)
Minimum:  1
Maximum:  99
mean:  49
Sum of all elements:  2482
Varience:  874.03046
Standard deviation:  29.564007


In [75]:
#another method to find varience and std:
import tensorflow_probability as tfp
tfp.stats.variance(test)

<tf.Tensor: shape=(), dtype=int64, numpy=874>

In [77]:
# FInd the positional maximum and minimum of the tensor
print("Positional maximun: ",tf.argmax(test).numpy(),":",test[tf.argmax(test).numpy()].numpy())
print("Positional minimun: ",tf.argmin(test).numpy(),":",test[tf.argmin(test).numpy()].numpy())

Positional maximun:  28 : 99
Positional minimun:  27 : 1


In [78]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
# find the posotional maximum of F
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor(removing all the single dimesnion)

Removes all the dimesions==1

In [80]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])
G,G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [81]:
G_squeezed=tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [82]:
#Create a list
some_list = [0,1,2,3]

#One hot:
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [83]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value=69,off_value=420)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 69, 420, 420, 420],
       [420,  69, 420, 420],
       [420, 420,  69, 420],
       [420, 420, 420,  69]], dtype=int32)>

### Squaring,log and square root

In [84]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [85]:
# Create a new tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [86]:
# Square root
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [87]:
# Take log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [88]:
# tf.math.segment_sum()---when 1, it wont be used for addition, else it will be used for addition, further research needed
test = tf.constant([[1,2,3,4],[1,-2,-3,-4],[5,6,7,8]])
tf.math.segment_sum(test,tf.constant([0,0,1]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 0, 0, 0],
       [5, 6, 7, 8]], dtype=int32)>

In [89]:
# Safe divsion with tf.math.divide_no_nan(x,y)
tf.math.divide_no_nan(12.0,0.0),tf.divide(12,0)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=inf>)

In [90]:
# Logical or operation
x=tf.constant([[True,False],[False,True]])
tf.math.logical_or(x,x)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True, False],
       [False,  True]])>

In [91]:
# multiplies a tensor by a scalar
tf.scalar_mul(5,test)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  5,  10,  15,  20],
       [  5, -10, -15, -20],
       [ 25,  30,  35,  40]], dtype=int32)>

In [92]:
test*5

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  5,  10,  15,  20],
       [  5, -10, -15, -20],
       [ 25,  30,  35,  40]], dtype=int32)>

In [93]:
# Squaring,log and sqrt
x = tf.range(1,101)
x=tf.reshape(x,(5,20))
x=tf.cast(x,dtype=tf.float32)
tf.square(x),tf.math.log(x),tf.sqrt(x)

(<tf.Tensor: shape=(5, 20), dtype=float32, numpy=
 array([[1.000e+00, 4.000e+00, 9.000e+00, 1.600e+01, 2.500e+01, 3.600e+01,
         4.900e+01, 6.400e+01, 8.100e+01, 1.000e+02, 1.210e+02, 1.440e+02,
         1.690e+02, 1.960e+02, 2.250e+02, 2.560e+02, 2.890e+02, 3.240e+02,
         3.610e+02, 4.000e+02],
        [4.410e+02, 4.840e+02, 5.290e+02, 5.760e+02, 6.250e+02, 6.760e+02,
         7.290e+02, 7.840e+02, 8.410e+02, 9.000e+02, 9.610e+02, 1.024e+03,
         1.089e+03, 1.156e+03, 1.225e+03, 1.296e+03, 1.369e+03, 1.444e+03,
         1.521e+03, 1.600e+03],
        [1.681e+03, 1.764e+03, 1.849e+03, 1.936e+03, 2.025e+03, 2.116e+03,
         2.209e+03, 2.304e+03, 2.401e+03, 2.500e+03, 2.601e+03, 2.704e+03,
         2.809e+03, 2.916e+03, 3.025e+03, 3.136e+03, 3.249e+03, 3.364e+03,
         3.481e+03, 3.600e+03],
        [3.721e+03, 3.844e+03, 3.969e+03, 4.096e+03, 4.225e+03, 4.356e+03,
         4.489e+03, 4.624e+03, 4.761e+03, 4.900e+03, 5.041e+03, 5.184e+03,
         5.329e+03, 5.476e+03

### Tensors and Numpy Compatibility

Tensorflow interacts with NumPy arrays

In [94]:
# create a tensor directly from Numpy array
J = tf.constant(np.array([3,4,62,3]))
J

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 3,  4, 62,  3])>

In [95]:
# Convert back the tensor back to numpy array
np.array(J),J.numpy()

(array([ 3,  4, 62,  3]), array([ 3,  4, 62,  3]))

In [96]:
# The default types of each differ
npJ=tf.constant(np.array([3.,46.,215.,6.]))
TensorJ=tf.constant([3.,7.,10.])
#check the dtype of each
TensorJ.dtype,npJ.dtype

(tf.float32, tf.float64)

### Finding access to GPU

In [97]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [98]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


## EXERCISE

In [99]:
# 1 Create a vector,scalar,matrix and tensor with values of your choosing using tf.constant()
a=tf.constant([1,2,3,4])
b=tf.constant(3)
c=tf.constant([[10,7],
             [3,4]])
a,b,c

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [100]:
# 2 Find the shape,rank and size of tensors created in 1
print(a.shape,b.shape,c.shape)
print(tf.rank(a).numpy(),tf.rank(b).numpy(),tf.rank(c).numpy())
print(tf.size(a).numpy(),tf.size(b).numpy(),tf.size(c).numpy())

(4,) () (2, 2)
1 0 2
4 1 4


In [101]:
# 3 Create two tensors containing random values between 0 and 1 with shape [5,300]
x = tf.random.uniform(shape=(5,30))
y = tf.random.uniform(shape=(5,30))
x,y

(<tf.Tensor: shape=(5, 30), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
         0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
         0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
         0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
         0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
         0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ],
        [0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
         0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
         0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
         0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ,
         0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869,
         0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ],
        [0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ,
         0.9707202 , 0.6779593 , 0.5641242 , 0.6253

In [102]:
# 4 Multiply the two tensors created in 3 using matrix multiplication
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 7.2341523,  8.23665  , 10.083019 , 10.768001 ,  8.554802 ],
       [ 7.2586665,  7.824765 ,  8.776067 ,  8.214538 ,  7.785835 ],
       [ 7.5698285,  8.359354 ,  9.295923 , 10.1651125,  8.594623 ],
       [ 6.0828457,  7.065919 ,  8.098655 ,  8.267043 ,  7.473749 ],
       [ 7.686407 ,  8.073922 , 11.181822 , 10.456645 ,  8.971823 ]],
      dtype=float32)>

In [103]:
# 5 Multiply two sensors created in 3 using dot product
tf.tensordot(x,tf.transpose(y),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 7.2341523,  8.23665  , 10.083019 , 10.768001 ,  8.554802 ],
       [ 7.2586665,  7.824765 ,  8.776067 ,  8.214538 ,  7.785835 ],
       [ 7.5698285,  8.359354 ,  9.295923 , 10.1651125,  8.594623 ],
       [ 6.0828457,  7.065919 ,  8.098655 ,  8.267043 ,  7.473749 ],
       [ 7.686407 ,  8.073922 , 11.181822 , 10.456645 ,  8.971823 ]],
      dtype=float32)>

In [104]:
# 6 Create a tensor with random values between 0 and 1 with shape [224,224,3]
test=tf.random.uniform(shape=(224,224,3))
test

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [105]:
# 7 Find the min and max values of the tensor created in 6
tf.reduce_min(test).numpy(),tf.reduce_max(test).numpy()

(1.0967255e-05, 0.9999902)

In [106]:
# 8 Create a tensor with shape [1,224,224,3] and squeeze it to [224,224,3]
test=tf.random.uniform(shape=(1,224,224,3))
test.shape,tf.squeeze(test).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [107]:
# 9 Create a tensor with shape [10] and find the index of the max value
test=tf.random.uniform(shape=(10,),minval=1,maxval=11)
test[tf.argmax(test)]==tf.reduce_max(test),tf.argmax(test)

(<tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [108]:
# 10 One-hot encode the tensor created in 9
tf.one_hot(tf.cast(test,dtype=tf.int32),depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>

In [109]:
x = tf.random.Generator.from_seed(42)
x = x.normal(shape=(3,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [110]:
tf.random.set_seed(42)
tf.random.uniform(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>